### ISSUE TITLE
Tone and Grammatical/Editing Mistakes

### ISSUE THREAD

**Issue by johnmarkdaniels** [learn-co-curriculum/dsc-lingalg-linear-equations#1]
The tone of this lesson and the other Linear Algebra lessons is very distracting. For those of us with little exposure to these concepts, this stuff is not simple. I have never been exposed to applications of sine waves, so telling me how simple and easy these concepts are just serves to make me feel stupid. The patronizing/condescending attitude in the writing is almost funny when contrasted with the glaring lack of copy editing and flagrant grammatical errors. The overall result is extremely distracting which makes reading these lessons a painful experience.

**Comment by bpurdy-ds** [comment]
We have modified this lessons a lot since summer 2019, and we have a very big revision coming with v3.0, so I shall close this. Commit: https://github.com/learn-co-curriculum/dsc-lingalg-linear-equations/issues/1#issue-454701876
